# .github/workflows/tag-and-changelog.yml
name: Auto Tag and Changelog

on:
  push:
    branches: [ "main" ]  # Trigger on push/merge to main
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Important: fetch all history for git describe

    - name: Get latest tag
      id: get_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "Latest tag: $latest_tag"
        echo "latest_tag=$latest_tag" >> "$GITHUB_OUTPUT"

    - name: Generate new tag (patch bump)
      id: new_tag
      run: |
        old=${{ steps.get_tag.outputs.latest_tag }}
        echo "Old tag: $old"
        version=${old#v}
        major=$(echo $version | cut -d. -f1)
        minor=$(echo $version | cut -d. -f2)
        patch=$(echo $version | cut -d. -f3)
        new_tag="v$major.$minor.$((patch+1))"
        echo "New tag: $new_tag"
        echo "new_tag=$new_tag" >> "$GITHUB_OUTPUT"

    - name: Generate changelog
      id: changelog
      run: |
        echo "Changelog since ${{ steps.get_tag.outputs.latest_tag }}:" > changelog.md
        git log ${{ steps.get_tag.outputs.latest_tag }}..HEAD --pretty=format:"- %s" >> changelog.md
        cat changelog.md

    - name: Commit and push tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag ${{ steps.new_tag.outputs.new_tag }}
        git push origin ${{ steps.new_tag.outputs.new_tag }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.new_tag.outputs.new_tag }}
        body_path: changelog.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
