name: Debricked
on:
  workflow_call:
    secrets:
      DEBRICKED_TOKEN:
        required: true

jobs:
  scan:
    name: Debricked
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: debricked/actions@v4
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
