name: Debricked SCA
on:
  workflow_dispatch:

jobs:
  debricked-sca-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Scan
      - uses: actions/checkout@v4
      - uses: debricked/actions@v4
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
