name: POC Mobb Actions

on:
  workflow_call:
    inputs:
      scan_file:
        required: true
        type: string
      repo_url:
        required: true
        type: string
      ref:
        required: true
        type: string
    secrets:
      MOBB_API_KEY:
        required: true

jobs:
  run_mobb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Run Bugsy Analyze
        run: >
          pnpm dlx mobbdev analyze --ci
          --scan-file "${{ inputs.scan_file }}"
          --repo "${{ inputs.repo_url }}"
          --ref "${{ inputs.ref }}"
          --api-key "${{ secrets.MOBB_API_KEY }}"
