name: POC Mobb Actions

on:
  workflow_call:
    inputs:
      scan_file:
        required: false
        type: string
        default: ''
      repo_url:
        required: false
        type: string
        default: ''
      ref:
        required: false
        type: string
        default: ''
      src_path:
        required: false
        type: string
        default: '.'
    secrets:
      MOBB_API_KEY:
        required: true

jobs:
  run_mobb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Run Bugsy Analyze (conditional scan-file / src-path)
        shell: bash
        run: |
          set -euo pipefail
          ARGS=( analyze --ci \
            --api-key "${{ secrets.MOBB_API_KEY }}" )

          # Preferir src_path quando informado (evita necessidade de token do SCM)
          if [[ -n "${{ inputs.src_path }}" ]]; then
            ARGS+=( --src-path "${{ inputs.src_path }}" )
          else
            # Caso não tenha src_path, exigir repo_url/ref
            if [[ -z "${{ inputs.repo_url }}" || -z "${{ inputs.ref }}" ]]; then
              echo "repo_url/ref não fornecidos e src_path vazio. Forneça src_path OU repo_url+ref." >&2
              exit 1
            fi
            ARGS+=( --repo "${{ inputs.repo_url }}" --ref "${{ inputs.ref }}" )
          fi

          # Adiciona scan-file se informado e existir
          if [[ -n "${{ inputs.scan_file }}" ]]; then
            if [[ -f "${{ inputs.scan_file }}" ]]; then
              ARGS+=( --scan-file "${{ inputs.scan_file }}" )
            else
              echo "scan_file informado mas não encontrado: ${{ inputs.scan_file }}" >&2
              exit 1
            fi
          fi

          pnpm dlx mobbdev "${ARGS[@]}" 
