name: POC Mobb Actions

on:
  workflow_call:
    inputs:
      scan_file:
        required: false
        type: string
        default: ''
      repo_url:
        required: true
        type: string
      ref:
        required: true
        type: string
    secrets:
      MOBB_API_KEY:
        required: true

jobs:
  run_mobb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: "Run Bugsy Analyze (per docs: repo/ref; optional scan-file)"
        shell: bash
        run: |
          set -euo pipefail
          ARGS=( analyze --ci \
            --repo "${{ inputs.repo_url }}" \
            --ref "${{ inputs.ref }}" \
            --api-key "${{ secrets.MOBB_API_KEY }}" )

          if [[ -n "${{ inputs.scan_file }}" ]]; then
            if [[ -f "${{ inputs.scan_file }}" ]]; then
              ARGS+=( --scan-file "${{ inputs.scan_file }}" )
            else
              echo "scan_file informado mas não encontrado: ${{ inputs.scan_file }}" >&2
              exit 1
            fi
          fi

          pnpm dlx mobbdev "${ARGS[@]}" 
