name: POC Mobb Actions

on:
  workflow_call:
    inputs:
      fortify_fpr:
        required: true
        type: string
    secrets:
      MOBB_API_KEY:
        required: true

jobs:
  run_mobb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: "Run Bugsy Analyze (Fortify FPR)"
        shell: bash
        run: |
          set -euo pipefail
          if [[ ! -f "${{ inputs.fortify_fpr }}" ]]; then
            echo "Fortify FPR não encontrado: ${{ inputs.fortify_fpr }}" >&2
            exit 1
          fi
          pnpm dlx mobbdev@latest analyze \
            --scan-file "${{ inputs.fortify_fpr }}" \
            --repo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
            --ref "$GITHUB_REF_NAME" \
            --api-key "${{ secrets.MOBB_API_KEY }}" \
            --ci 
