name: POC Mobb Actions

on:
  workflow_call:
    inputs:
      scan_file:
        required: false
        type: string
        default: ''
      fortify_fpr:
        required: false
        type: string
        default: ''
      sarif_artifact_name:
        required: false
        type: string
        default: ''
    secrets:
      MOBB_API_KEY:
        required: true

jobs:
  run_mobb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: "Download SARIF artifact (if provided)"
        if: ${{ inputs.sarif_artifact_name != '' && inputs.scan_file == '' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.sarif_artifact_name }}
          path: artifacts

      - name: "Run Bugsy Analyze (SARIF or Fortify FPR)"
        shell: bash
        run: |
          set -euo pipefail

          # Determine SCAN_FILE path
          SCAN_FILE="${{ inputs.scan_file }}"

          if [[ -z "$SCAN_FILE" && -n "${{ inputs.sarif_artifact_name }}" ]]; then
            # Find SARIF inside downloaded artifacts
            if [[ -d artifacts ]]; then
              found=$(find artifacts -type f -name "*.sarif" | head -n1 || true)
              if [[ -n "$found" ]]; then
                SCAN_FILE="$found"
              fi
            fi
          fi

          if [[ -n "$SCAN_FILE" ]]; then
            if [[ ! -f "$SCAN_FILE" ]]; then
              echo "scan_file informado mas não encontrado: $SCAN_FILE" >&2
              exit 1
            fi
            pnpm dlx mobbdev analyze --ci \
              --scan-file "$SCAN_FILE" \
              --api-key "${{ secrets.MOBB_API_KEY }}"
            exit 0
          fi

          if [[ -n "${{ inputs.fortify_fpr }}" ]]; then
            if [[ ! -f "${{ inputs.fortify_fpr }}" ]]; then
              echo "Fortify FPR não encontrado no caminho: ${{ inputs.fortify_fpr }}" >&2
              exit 1
            fi
            pnpm dlx mobbdev analyze --ci \
              --scan-file "${{ inputs.fortify_fpr }}" \
              --api-key "${{ secrets.MOBB_API_KEY }}"
            exit 0
          fi

          echo "É necessário informar scan_file (SARIF) ou fortify_fpr (.fpr), ou fornecer sarif_artifact_name para download automático." >&2
          exit 1 
